# SonarCloud project configuration for cloud.aws_ops
# Complete documentation: https://docs.sonarqube.org/latest/analysis/analysis-parameters/

sonar.projectKey=ansible-collections_cloud.aws_ops
sonar.organization=ansible-collections
sonar.sources=.
sonar.projectName=cloud.aws_ops
sonar.python.coverage.reportPaths=coverage.xml

sonar.tests=tests/integration
sonar.python.version=3.12
sonar.newCode.referenceBranch=main

sonar.exclusions=tests/**,.tox/**
