[tox]
minversion = 4.0
skipsdist = True

[common]
format_dirs = {toxinidir}/plugins {toxinidir}/tests

[testenv]
deps = -r {toxinidir}/test-requirements.txt
install_command = pip install {opts} {packages}

[testenv:ansible-lint]
description = Run ansible-lint
deps =
  ansible-lint >= 25.1.2
commands = ansible-lint

[testenv:black]
description = Lint against "black" formatting standards
deps =
  black >= 24.0, < 25.0
commands =
  black --check --diff {[common]format_dirs}

[testenv:black_format]
description = Apply "black" formatting
deps =
  {[testenv:black]deps}
commands =
  black -v {[common]format_dirs}

[testenv:flake8]
deps =
  flake8
commands =
  flake8 {[common]format_dirs}

[testenv:isort]
description = Lint for import sorting
deps =
  isort
commands =
  isort --check-only --diff {[common]format_dirs}

[testenv:isort_format]
description = Sort imports
deps =
  {[testenv:isort]deps}
commands =
  isort -v {[common]format_dirs}

[testenv:format]
deps =
  {[testenv:black]deps}
  {[testenv:isort]deps}
commands =
  {[testenv:black]commands}
  {[testenv:isort]commands}

[testenv:linters]
deps =
  {[testenv:black]deps}
  {[testenv:flake8]deps}
  {[testenv:isort]deps}
  {[testenv:ansible-lint]deps}
commands =
  {[testenv:black]commands}
  {[testenv:flake8]commands}
  {[testenv:isort]commands}
  {[testenv:ansible-lint]commands}

[testenv:sanity]
deps = ansible
commands = ansible-test sanity

[flake8]
exclude = .git,.tox,tests/output
ignore = E501, W503, W504, E402
max-line-length = 160
builtins = _
