---
- name: Create/Delete API gateway with lambda integration
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"
  block:
    - name: Include file
      ansible.builtin.include_tasks: '{{ item }}'
      loop:
        - lambda.yml
        - apigateway.yml
      loop_control:
        label: "{{ item }}"
