---
# tasks file for roles/enable_cloudtrail_encryption_with_kms

- name: Run 'enable_cloudtrail_encryption_with_kms' role
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"

  block:
    - name: Fail when 'enable_cloudtrail_encryption_with_kms_trail_name' is not defined
      ansible.builtin.fail:
        msg: The ARN or name of the trail you want to update to be encrypted must be defined as enable_cloudtrail_encryption_with_kms_trail_name
      when: enable_cloudtrail_encryption_with_kms_trail_name is not defined

    - name: Fail when 'enable_cloudtrail_encryption_with_kms_kms_key_id' is not defined
      ansible.builtin.fail:
        msg: The ARN, key ID, or the key alias of the customer managed key you want to use to encrypt the trail must be defined as enable_cloudtrail_encryption_with_kms_kms_key_id
      when: enable_cloudtrail_encryption_with_kms_kms_key_id is not defined

    - name: Gather information about the trail
      amazon.aws.cloudtrail_info:
        trail_names:
          - "{{ enable_cloudtrail_encryption_with_kms_trail_name }}"
      register: enable_cloudtrail_encryption_with_kms__trail_info

    - name: Fail when the trail does not exist
      ansible.builtin.fail:
        msg: "The trail does not exist: {{ enable_cloudtrail_encryption_with_kms_trail_name }}"
      when: enable_cloudtrail_encryption_with_kms__trail_info.trail_list | length == 0

    - name: Gather information about the KMS key
      amazon.aws.kms_key_info:
        key_id: "{{ enable_cloudtrail_encryption_with_kms_kms_key_id }}"
      register: enable_cloudtrail_encryption_with_kms__kms_key_info

    - name: Gather information about the KMS key using alias
      amazon.aws.kms_key_info:
        alias: "{{ enable_cloudtrail_encryption_with_kms_kms_key_id }}"
      register: enable_cloudtrail_encryption_with_kms__kms_key_info
      when: enable_cloudtrail_encryption_with_kms__kms_key_info.kms_keys | length == 0

    - name: Fail when the KMS key does not exist
      ansible.builtin.fail:
        msg: "The KMS key does not exist: {{ enable_cloudtrail_encryption_with_kms_trail_name }}"
      when: enable_cloudtrail_encryption_with_kms__kms_key_info.kms_keys | length == 0

    - name: Enable encryption on the trail
      amazon.aws.cloudtrail:
        state: present
        name: "{{ enable_cloudtrail_encryption_with_kms_trail_name }}"
        kms_key_id: "{{ enable_cloudtrail_encryption_with_kms__kms_key_info.kms_keys.0.key_arn }}"
        s3_bucket_name: "{{ enable_cloudtrail_encryption_with_kms__trail_info.trail_list.0.s3_bucket_name }}"
        s3_key_prefix: "{{ enable_cloudtrail_encryption_with_kms__trail_info.trail_list.0.s3_key_prefix | default(omit ) }}"

    - name: Verify that encryption has been enabled on the CloudTrail trail
      amazon.aws.cloudtrail_info:
        trail_names:
          - "{{ enable_cloudtrail_encryption_with_kms_trail_name }}"
      register: enable_cloudtrail_encryption_with_kms__verify_encryption

    - name: Assert that AWS CloudTrail trail was successfully encrypted
      ansible.builtin.assert:
        that:
          - enable_cloudtrail_encryption_with_kms__verify_encryption.trail_list.0.kms_key_id == enable_cloudtrail_encryption_with_kms__kms_key_info.kms_keys.0.key_arn
        success_msg: AWS CloudTrail trail was successfully encrypted
        fail_msg: AWS CloudTrail trail was not successfully encrypted
