name: Integration
on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*

jobs:
  splitter:
    runs-on: ubuntu-latest
    env:
      source_dir: "cloud_awsops"
    outputs:
      targets: ${{ steps.splitter.outputs.targets }}
      test_jobs: ${{ steps.splitter.outputs.jobs }}
    steps:
      - name: Checkout collection
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          path: ${{ env.source_dir }}
          fetch-depth: "0"

      - name: List changes for pull request
        id: splitter
        uses: ansible/cloud-content-ci-automation/.github/actions/ansible_test_splitter@a93c78e1d842d4ee8961769110d88ac16bcc217a  # main, Commits on May 15, 2026
        with:
          collections_to_test: ${{ env.source_dir }}
          total_jobs: 8
          base_ref: "${{ github.event.pull_request.base.ref }}"

      - name: Display splitter output
        run: |
          echo "test_targets=${{ steps.splitter.outputs.targets }}"
          echo "test_jobs=${{ steps.splitter.outputs.jobs }}"
        shell: bash
  integration_tests:
    runs-on: ubuntu-latest
    needs:
      - splitter
    if: ${{ needs.splitter.outputs.targets != '' }}
    # environment: protected  # requires manual approval within GitHub Actions to proceed
    env:
      source: "./source"
      ansible_version: "milestone"
      python_version: "3.13"
      ansible_test_splitter_targets: "${{ needs.splitter.outputs.targets }}"
    strategy:
      fail-fast: false
      matrix:
        workflow-id: ${{ fromJson(needs.splitter.outputs.test_jobs) }}
    name: "integration-${{ matrix.workflow-id }}"
    steps:
      - name: Read job targets
        id: read-targets
        uses: ansible/cloud-content-ci-automation/.github/actions/ansible_read_targets@0b891487c4170ef856f02313c66cb1c776814c42  # main, committedon Apr 1, 2026
        with:
          job_id: "${{ matrix.workflow-id }}"
          all_targets: "${{ env.ansible_test_splitter_targets }}"

      - name: Display ansible test targets
        run: |
          echo "ansible_test_targets -> ${{ steps.read-targets.outputs.job_targets }}"
        shell: bash

      - name: Create AWS/sts session credentials
        uses: ansible/ansible-test-auth@008750a5bf07124c3ab86d30d73d7319d7518f36  # v1.0.0, committed on Mar 13, 2026

      - name: Run integration tests
        uses: ansible-community/ansible-test-gh-action@d3a8ec7a59694e25e210fcd44738910149537f0e  # v1.17.0, committed on Aug 6, 2025
        with:
          ansible-core-version: ${{ env.ansible_version }}
          origin-python-version: ${{ env.python_version }}
          testing-type: integration
          target-python-version: ${{ env.python_version }}
          target: ${{ steps.read-targets.outputs.job_targets }}
          test-deps: >-
            git+https://github.com/ansible-collections/amazon.aws.git,main
            git+https://github.com/ansible-collections/community.aws.git,main
            community.crypto
            community.general
          pre-test-cmd: python -m pip install -r tests/integration/constraints.txt -r tests/integration/requirements.txt
